export enum DashboardActionTypes {
	API_RESPONSE_SUCCESS = '@@dashboard/API_RESPONSE_SUCCESS',
	API_RESPONSE_ERROR = '@@dashboard/API_RESPONSE_ERROR',
	API_RESPONSE_LOADING = '@@dashboard/API_RESPONSE_LOADING', // ✅ new

	GET_DAILY_ACTIVE_USERS = '@@dashboard/GET_DAILY_ACTIVE_USERS',
	GET_VERIFIED_NOT_VERIFIED_USERS = '@@dashboard/GET_VERIFIED_NOT_VERIFIED_USERS',
	GET_TOTAL_ACTIVE_USERS = '@@dashboard/GET_TOTAL_ACTIVE_USERS',
	GET_REGISTERED_USERS = '@@dashboard/GET_REGISTERED_USERS',
	GET_NEW_SIGNUP_USERS = '@@dashboard/GET_NEW_SIGNUP_USERS',
	GET_NEW_SIGNUP_USERS_NOT_ONBOARDING = '@@dashboard/GET_NEW_SIGNUP_USERS_NOT_ONBOARDING',
}
