export enum RewardsActionTypes {
	API_RESPONSE_SUCCESS = '@@rewards/API_RESPONSE_SUCCESS',
	API_RESPONSE_ERROR = '@@rewards/API_RESPONSE_ERROR',

	GET_REWARDS = '@@rewards/GET_REWARDS',
	REQUEST_APPROVED = '@@rewards/REQUEST_APPROVED',
	REQUEST_REJECTED = '@@rewards/REQUEST_REJECTED',
}
