export enum UsersActionTypes {
	API_RESPONSE_SUCCESS = '@@users/API_RESPONSE_SUCCESS',
	API_RESPONSE_ERROR = '@@users/API_RESPONSE_ERROR',
	API_RESPONSE_LOADING = '@@users/API_RESPONSE_LOADING', // ✅ new

	GET_USERS = '@@users/GET_USERS',
}
