export enum BookingDetailsActionTypes {
	API_RESPONSE_SUCCESS = '@@rewards/API_RESPONSE_SUCCESS',
	API_RESPONSE_ERROR = '@@rewards/API_RESPONSE_ERROR',
	API_RESPONSE_LOADING = '@@rewards/API_RESPONSE_LOADING', // ✅ new

	GET_BOOKING_DETAILS = '@@rewards/GET_BOOKING_DETAILS',
	GET_AMANDUS_DETAILS = '@@rewards/GET_AMANDUS_DETAILS',
	GET_BEST_DETAILS = '@@rewards/GET_BEST_DETAILS',
}
